USE MarcaModelo
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Modelo](
	[IDModelo] [int] IDENTITY(1,1) NOT NULL,
	[IDMarca] [int] NOT NULL,
	[Descripcion] [varchar](50) NOT NULL,
	[Estado] [char](1) NOT NULL
 CONSTRAINT [PK_Modelo] PRIMARY KEY CLUSTERED 
(
	[IDModelo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


