USE MarcaModelo
INSERT INTO Marca VALUES('Epson', 'A')
GO
INSERT INTO Marca VALUES('NCR', 'A')
GO
SELECT * FROM Marca
GO

INSERT INTO Modelo VALUES(1, '2028', 'A')
GO
INSERT INTO Modelo VALUES(1, '2020 T', 'A')
GO
INSERT INTO Modelo VALUES(1, '2050 PLUS', 'A')
GO
INSERT INTO Modelo VALUES(1, '2005', 'A')
GO
INSERT INTO Modelo VALUES(1, '2008', 'A')
GO

INSERT INTO Modelo VALUES(2, 'TM 2000AF+', 'A')
GO
INSERT INTO Modelo VALUES(2, 'TM 300 A/F', 'A')
GO
INSERT INTO Modelo VALUES(2, 'TM 300 A/F+', 'A')
GO
INSERT INTO Modelo VALUES(2, 'TM-285F', 'A')
GO
INSERT INTO Modelo VALUES(2, 'TM-U950F', 'A')
GO
SELECT * FROM Modelo
GO
